### PR TITLE
Add os x jobs to ci (arm and x86) + more extensive ubuntu jobs

### LINKED ISSUE #81: No CI for macos
Currently there is only a ci for Ubuntu on x86 . I suggest the creation of a workflow which compiles on macos, now the build issues that arise from building on an arm based apple machine have been resolved. 

@vgvassilev @alexander-penev If either of you have any requirements on what you would like to see for such a workflow please put them in the comments below.

My first step towards doing this workflow would be to develop/improve the macos ci workflow for CppInterOp (issue https://github.com/compiler-research/CppInterOp/issues/138 ). I am happy to be assigned to both these issues.

### PR DESCRIPTION
**Pull request by mcbarton**
Adds Add os x jobs to ci (arm and x86)
More extensive ubuntu jobs
Updates patches to match those in CppInterOp
Fixes https://github.com/compiler-research/xeus-clang-repl/issues/81

### CODE REVIEW

**Comment by mcbarton** [comment]
@vgvassilev can you clear the cache for me, so that I can fix the cache for the cling based jobs?

**Comment by mcbarton** [comment]
> @vgvassilev can you clear the cache for me, so that I can fix the cache for the cling based jobs?

@vgvassilev After you clear the cache, please activate the ci manually. It should get all green ticks. At that point I will consider the PR ready for review.

**Comment by vgvassilev** [comment]
Done.

**Comment by mcbarton** [comment]
@alexander-penev Can you review this PR for me?

**Review by alexander-penev — APPROVED** [review]

**Pull request merged**
